version: 2
jobs:
  kernel_e50:
    docker:
      - image: lochnair/mtk-buildenv:latest
    working_directory: /build/
    steps:
      - run:
          command: su-exec root apt-get update
          working_directory: /build/kernel_e50
      - run:
          command: su-exec root apt-get -y install bc bison flex git
          working_directory: /build/kernel_e50
      - run:
          command: git clone -b v1.10.10/master https://github.com/Lochnair/kernel_e50.git .
          working_directory: /build/kernel_e50
      - run:
          command: make ARCH=mips ubnt_er_e50_defconfig
          working_directory: /build/kernel_e50
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mipsel-mtk-linux- prepare modules_prepare
          working_directory: /build/kernel_e50
      - run:
          command: rm -rf tmp && mkdir tmp
          working_directory: /build/kernel_e50
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mipsel-mtk-linux- vmlinux modules
          working_directory: /build/kernel_e50
      - run:
          command: make ARCH=mips CROSS_COMPILE=mipsel-mtk-linux- INSTALL_MOD_PATH=destdir modules_install
          working_directory: /build/kernel_e50
      - run:
          command: rm -rf .git Documentation
          working_directory: /build/kernel_e50
      - persist_to_workspace:
          root: /build
          paths:
            - kernel_e50
  clone_module:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - run:
          command: git clone -b v0.0.20200215 git://git.zx2c4.com/wireguard-linux-compat .
          working_directory: /build/module
      - run:
          command: curl -L https://gist.githubusercontent.com/Lochnair/805bf9ab96742d0fe1c25e4130268307/raw/29e37d43a5247a3f2584ef0d6d553ee9a4532e12/only-use-__vmalloc-for-now.patch | patch compat.h
          working_directory: /build/module/src/compat
      - run:
          command: sed -i 's/ --dirty//g' src/Makefile
          working_directory: /build/module
      - persist_to_workspace:
          root: /build
          paths:
            - module
  module_e50:
    docker:
      - image: lochnair/mtk-buildenv:latest
    working_directory: /build/
    steps:
      - attach_workspace:
          at: /build
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mipsel-mtk-linux- KERNELDIR=/build/kernel_e50 module
          working_directory: /build/module/src
      - run:
          command: mipsel-mtk-linux-strip --strip-debug wireguard.ko
          working_directory: /build/module/src
      - run:
          command: mv wireguard.ko wireguard_e50.ko
          working_directory: /build/module/src
      - persist_to_workspace:
          root: /build
          paths:
            - module/src/wireguard_e50.ko
  tools_mipsel:
    docker:
      - image: lochnair/musl-buildenv:mipsel
    working_directory: /build/
    steps:
      - run:
          command: git clone -b v1.0.20200206 git://git.zx2c4.com/wireguard-tools .
          working_directory: /build/tools-mipsel
      - run:
          command: CC="mipsel-linux-musl-gcc" LDLIBS="-static" make -j5
          working_directory: /build/tools-mipsel/src
      - run:
          command: mipsel-linux-musl-strip --strip-unneeded wg
          working_directory: /build/tools-mipsel/src
      - persist_to_workspace:
          root: /build
          paths:
            - tools-mipsel/src/wg
  package:
    docker:
      - image: debian
    working_directory: /build/
    steps:
      - run: apt-get update
      - run: apt-get -y install ca-certificates
      - attach_workspace:
          at: /build
      - store_artifacts:
          path: /build/module/src/wireguard_e50.ko
          destination: wireguard_e50.ko
      - store_artifacts:
          path: /build/tools-mipsel/src/wg
          destination: wg-mipsel

workflows:
  version: 2

  build_modules:
    jobs:
      - kernel_e50
      - clone_module
      - module_e50:
          requires:
            - clone_module
            - kernel_e50
      - tools_mipsel
      - package:
          requires:
            - module_e50
            - tools_mipsel
